/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QrCodeRouteImport } from './routes/qr-code'
import { Route as ZipRouteImport } from './routes/zip'
import { Route as ExportXlsRouteImport } from './routes/export/xls'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCodeRoute = QrCodeRouteImport.update({
  id: '/qr-code',
  path: '/qr-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ZipRoute = ZipRouteImport.update({
  id: '/zip',
  path: '/zip',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportXlsRoute = ExportXlsRouteImport.update({
  id: '/export/xls',
  path: '/export/xls',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/qr-code': typeof QrCodeRoute
  '/zip': typeof ZipRoute
  '/export/xls': typeof ExportXlsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/qr-code': typeof QrCodeRoute
  '/zip': typeof ZipRoute
  '/export/xls': typeof ExportXlsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/qr-code': typeof QrCodeRoute
  '/zip': typeof ZipRoute
  '/export/xls': typeof ExportXlsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/qr-code' | '/zip' | '/export/xls'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/qr-code' | '/zip' | '/export/xls'
  id: '__root__' | '/' | '/qr-code' | '/zip' | '/export/xls'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QrCodeRoute: typeof QrCodeRoute
  ZipRoute: typeof ZipRoute
  ExportXlsRoute: typeof ExportXlsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-code': {
      id: '/qr-code'
      path: '/qr-code'
      fullPath: '/qr-code'
      preLoaderRoute: typeof QrCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zip': {
      id: '/zip'
      path: '/zip'
      fullPath: '/zip'
      preLoaderRoute: typeof ZipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export/xls': {
      id: '/export/xls'
      path: '/export/xls'
      fullPath: '/export/xls'
      preLoaderRoute: typeof ExportXlsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QrCodeRoute: QrCodeRoute,
  ZipRoute: ZipRoute,
  ExportXlsRoute: ExportXlsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
